server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/** , /staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default zone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-64837756.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa94qol946iu2bXi5d7
    client-secret: _PKGTKUuOHNvpNlstQu3rG7Pn0ah1OKPkCd6zPk-
    scopes: openid, profile, email, offline_access
