server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085


#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default zone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true


okta:
  oauth2:
    issuer: https://dev-64837756.okta.com/oauth2/default
    audience: api://default